### ISSUE TITLE
inconsistent-ness?

### ISSUE THREAD

**Issue by gosoccerboy5** [FunctionalMetatable/numbers-man-detector#10]
in the lua and js folders, the program exports a default function...
https://github.com/FunctionalMetatable/numbers-man-detector/blob/526559d871c58ab0c2690ea37c97f8fe13fb29fb/lua/script.lua#L3-L10
https://github.com/FunctionalMetatable/numbers-man-detector/blob/526559d871c58ab0c2690ea37c97f8fe13fb29fb/javascript/index.js#L3-L6
whereas in the python and dart folders it instead creates a function which you will have to explicitly use
https://github.com/FunctionalMetatable/numbers-man-detector/blob/526559d871c58ab0c2690ea37c97f8fe13fb29fb/python/main.py#L2-L3
https://github.com/FunctionalMetatable/numbers-man-detector/blob/526559d871c58ab0c2690ea37c97f8fe13fb29fb/dart/main.dart#L5

I'm not sure if you can actually export a default function or value in Dart or python, and it doesn't make much of a difference, so I guess this doesn't really matter anyways

**Comment by Quantum-Codes** [comment]
Where does this detect the numbers man?? It doesn't look on scratch website or stuff...  someone explain what's the code searching in?
